theme: neomigim
title: میگیم از دیدگاهی شاید متفاوت

url: http://migim.ir
permalink: /:title.html
#paginate_path: "/blog/page:num/"
paginate: 5
pagination_dir: blog

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
