theme: neomigim
title: میگیم دیدگاهی متفاوت

url: http://migim.ir
permalink: /:title.html
#paginate_path: "/blog/page:num/"
paginate: 3 
pagination_dir: blog

plugins:
  - jekyll-feed
  - jekyll-paginate
