# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://migim.ir" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: میگیم
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "روزنوشت‌های یک علاقه‌مند به کامپیوتر" # used by search engines

  # Header and footer text
  header_text: > 
  header_text_feature_image:
  footer_text: >
   <p>محتوای این وبسایت تحت <a href="https://creativecommons.org/licenses/by/4.0/deed.fa" >لیسانس کریتیو </a> کامنز منتشر می‌شود</p>
   <p>همچنین قالب وبسایت انشعابی از قالب <a href="https://github.com/rohanchandra/type-theme">Type Theme</a> می باشد و توسط سرورهای <a href="https://github.com">گیت‌هاب</a> بر روی سیستم مدیریت محتوای <a href="http://jekyllrb.com">جکیل</a> پشتیبانی می‌شود</p>

  # Icons
  rss: true
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "migim"
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: 
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  muut_community_name: # From muut.com settings, e.g. "muttcommunityname"
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "دنبال‌کنید در"
  str_rss_follow: "خوراک RSS"
  str_email: "ایمیل"
  str_next: "بعدی"
  str_prev: "قبلی"
  str_continue_reading: "ادامه مطلب"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed

gems:
  - jekyll-paginate


theme: jekyll-theme-slate