theme: neomigim
title: میم-ر 
description: محمد-رضا هستم
author: محمدرضا مقیمی
logo: /assets/img/mimr-prof150wp.svg.png
lang: fa_IR

social:
        name: میم-ر
        links:
                - http://github.com/mimr9
                - http://yourshot.nationalgeographic.com/profile/1501852/
                - https://www.linkedin.com/in/mohammadreza-moghimi/

url: http://mimr.ir
permalink: /:title.html
#paginate_path: "/blog/page:num/"
paginate: 5
pagination_dir: blog

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
